# Generated by Django 3.2.15 on 2022-10-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20221013_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(through='pizza.PizzaTopping', to='pizza.Topping'),
        ),
    ]
