# Generated by Django 3.2.15 on 2022-10-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(related_name='toppings', through='pizza.PizzaTopping', to='pizza.Topping'),
        ),
    ]
