# Generated by Django 3.2.15 on 2022-10-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_alter_pizza_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza'),
        ),
        migrations.AlterField(
            model_name='pizzatopping',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza'),
        ),
        migrations.AlterField(
            model_name='pizzatopping',
            name='toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.topping'),
        ),
    ]
