# Generated by Django 3.2.15 on 2022-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0008_auto_20221013_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(related_name='topping', through='pizza.PizzaTopping', to='pizza.Topping'),
        ),
    ]
